# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY 404islands-app/package*.json ./
RUN npm install
COPY 404islands/404islands-app/src/backend ./src/backend

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD ["node", "src/backend/server.js"]